Add documentation for the API section
studiometa/js-toolkit pull request #120
Opened 2021-07-19 15:47 UTC by KeziahMoselle

- [ ] Create the lifecycle diagram (Inspired by [vuejs.org](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)
- [ ] Add examples for each Interface methods
	- [ ] #mounted() Lifecycle hooks
	- [ ] #loaded() Lifecycle hooks
	- [ ] #destroyed() Lifecycle hooks
	- [ ] #terminated() Lifecycle hooks
	- [ ] #scrolled(props) Service hooks
	- [ ] #resized(props) Service hooks
	- [ ] #keyed(props) Service hooks
	- [ ] #moved(props) Service hooks
	- [ ] #ticked(props) Service hooks
	- [ ] #on＜Event＞(event) Event handlers
	- [ ] #on＜RefOrChildName＞＜Event＞(event, index)
- [ ] Add examples for each Instance methods
	- [ ] `$log(…content)`
	- [ ] `$on(event, callback)`
	- [ ] `$once(event, callback)`
	- [ ] `$off(event[, callback])`
	- [ ] `$emit(event[, …args])`
	- [ ] `$mount()`
	- [ ] `$update()`
	- [ ] `$destroy()`
	- [ ] `$terminate()`
- [ ] Add examples for each Events
	- [ ] `mounted`
	- [ ] `loaded`
	- [ ] `scrolled`
	- [ ] `resized`
	- [ ] `keyed`
	- [ ] `moved`
	- [ ] `ticked`
	- [ ] `updated`
	- [ ] `destroyed`
	- [ ] `terminated`
	- [ ] `get:options`
	- [ ] `get:refs`
	- [ ] `get:children`

2021-07-19 15:59 UTC, titouanmathis commented on packages/docs/api/index.md
> +@TODO Explain the mounted hook
**note:** Some advanced explanation can be done in the **Guide** section, we can keep things to a minimum here and link to a section where the lifecycle of a component is explained.

2021-07-19 15:59 UTC, titouanmathis commented on packages/docs/api/index.md
> +Called after the instance has been loaded.
**issue :** This hook is called when the `load` event is fired on the `window`

2021-07-19 16:02 UTC, KeziahMoselle commented on packages/docs/api/index.md
> +Called after the instance has been loaded.
That is true, I just copy pasted the example above for now

2021-07-19 16:02 UTC, KeziahMoselle commented on packages/docs/api/index.md
> +@TODO Explain the mounted hook
Okay! Will do

2021-11-01 18:29 UTC, titouanmathis requested changes
Nice additions! 

Some breaking changes were introduced in the v2 making some items added obsolete.

2021-11-01 18:29 UTC, titouanmathis commented on packages/docs/api/index.md
>  ### `$once(event, callback)`
**issue :** The `$once` method has been removed 

The same behaviour can be achieved with the `$on` method:

```js
this.$on('event', () => {}, { once: true });
```

2021-11-01 18:29 UTC, titouanmathis commented on packages/docs/api/index.md
> +    this.$off('get:refs')
**issue:** The `$off` method needs 2 parameters now, this will not work anymore

```js
const handler = () => {};

this.$on('event', handler);
this.$off('event', handler);
```

2021-11-01 18:29 UTC, titouanmathis commented on packages/docs/api/index.md
> +```js
**suggestion:** Add highlight for the important parts

````
```js{6,10}
````

See https://vitepress.vuejs.org/guide/markdown.html#line-highlighting-in-code-blocks.

2021-11-16 15:05 UTC, titouanmathis commented
This was merged with some edits in #161, thanks @KeziahMoselle!

2021-11-16 15:05 UTC, closed without merging