feature/vue-app-component
studiometa/js-toolkit pull request #148
Opened 2021-09-13 10:15 UTC by jeremschelb

Refer to PR #132

2021-09-13 10:19 UTC, titouanmathis reviewed
Everything seems good, we just need to add tests for the new decorator.

2021-09-13 15:32 UTC, titouanmathis requested changes

2021-09-13 15:32 UTC, titouanmathis commented on packages/js-toolkit/decorators/withVue.js
> +
**issue:** Test the `vue` refs and throw an error if it not an instance of `HTMLElement`

2021-09-20 09:58 UTC, titouanmathis commented on packages/js-toolkit/decorators/withVue.js
> +
This should fix the `Argument of type 'Base | HTMLElement | HTMLElement[] | Base[] | Promise<Base> | Promise<Base>[]' is not assignable to parameter of type 'string | Element'.` error above.

2021-09-20 10:02 UTC, titouanmathis commented on packages/js-toolkit/decorators/withVue.js
> +
**chore:** Add an empty static `vueConfig` property

```js
static vueConfig;
```

This will help with the `Property 'vueConfig' does not exist on type 'Function'.` error above. We might need to cast the `this.constructor` line 25:

```js
const { vueConfig } = /** @type {typeof withVue} */ (this.constructor);
```

2021-10-29 18:52 UTC, perruche approved these changes
👍

2021-10-30 08:48 UTC, titouanmathis commented on packages/demo/package.json
> +    "vue": "^2.6.14"
I had the same idea, I was thinking about doing a `withVue2` decorator and migrate the existing to work with Vue 3.

2021-10-30 08:48 UTC, titouanmathis commented on packages/demo/src/js/components/CustomComponent.vue
> +</template>
Good idea 👍

2021-10-31 19:25 UTC, titouanmathis commented on packages/demo/src/js/components/CustomComponent.vue
> +</template>
I suggest to improve the example later to avoid blocking the merge of this PR.

2021-11-01 08:40 UTC, merged

2021-11-01 18:26 UTC, perruche commented on packages/demo/src/js/components/CustomComponent.vue
> +</template>
yeah sure, not an important point