Add managing refs section
studiometa/js-toolkit pull request #168
Opened 2021-11-29 16:58 UTC by KeziahMoselle

There is still rewording to do but it should be good enough. Feel free to propose things to make it better!

2021-11-30 08:31 UTC, perruche reviewed
Great addition.
Mostly nitpicking wording syntax to be consistant

2021-11-30 08:31 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +A ref is a *reference* to a DOM element. It allow us to quickly access HTML elements. We can define single or multiple refs that we can easily use in our component without manually querying DOM eleme
**suggestion**: Avoid using "we", "us", "i" in the documentation as they are quite unsuitable in formal writing

**reword exemple**:
A ref is a *reference* to a DOM element. It allows to quickly access HTML elements. Define single or multiple refs to easily use them in a component without manually querying DOM elements.

2021-11-30 08:31 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +    // `btn` is a single ref.
**suggestion**: provide the return type instead of phrasing ?

2021-11-30 08:31 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +First we need to declare the refs we want to use in our component, here we want to use a `btn`.
**personnal opinion**: The sections `single refs` and `multiple refs` seems repetitive since it's already explain above in `Defining refs`. Should defining refs be about where to register the refs in JS and in HTML ?

2021-11-30 08:31 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +```
**issue** There is no mention on the link between JS and HTML refs, should the exemple contain both HTML and JS code ? 
Maybe also add that if a ref is not define in the config it won't be available

2021-11-30 08:31 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +    this.$refs.items; // [<li data-ref="items[]">#1</li>, ...]
**question**: Isn't this is returning the Component instance and not the HTML element (which is in `this.$refs.btn.$el`) ?

2021-11-30 18:38 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-refs.md
> +    this.$refs.items; // [<li data-ref="items[]">#1</li>, ...]
The v2 no longer resolves component instances when a ref is also a component.

```html
<div data-component="Parent">
  <div data-ref="item" data-component="Child"></div>
</div>
```
```js
class Parent extends Base {
  static config = {
    name: 'Parent',
    refs: ['item'],
    components: { Child },
  };

  mounted() {
    console.log(this.$refs); // v1 → { item: Child }
    console.log(this.$refs); // v2 → { item: <div data-ref="item" data-component="Child"></div> }
  }
}
```

This was changed in order for refs to be more predictable about what they are. The `$children` property must be used to access child components' instances.

2021-11-30 18:40 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-refs.md
> +    // `btn` is a single ref.
I think that the comments here can be misleading, we could improve it by displaying each ref on a single line:

```js
    refs: [
      'btn', // single ref
      'items[]', // multiple ref with the `[]` suffix
    ],
```

2021-11-30 18:48 UTC, titouanmathis requested changes
This is a good first draft, well done @KeziahMoselle!

I have some things in mind that should be added, but they are not yet well thought. I will get back to you later on the subject.

2021-11-30 18:48 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-refs.md
> +
**suggestion:** add a small section about the preferred naming convention for multiple refs

- camelCase
- plural

2021-11-30 18:48 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-refs.md
> +The [`refs` property](/api/configuration.html#config-refs) of the static `config` object should be used to define what refs will be used in the component otherwise it can't be accessed. This property
**detail:** Change `will be used` with `will be available` 
**detail:** Remove unnecessary precision

```suggestion
The [`refs` property](/api/configuration.html#config-refs) of the static `config` object should be used to define what refs will be available in the component. This property requires an array of string that correspond to the refs names in the HTML code.
```

2021-11-30 19:23 UTC, perruche commented on packages/docs/guide/introduction/managing-refs.md
> +    this.$refs.items; // [<li data-ref="items[]">#1</li>, ...]
i confused myself, this is talking about refs and not components, of course it return HTLMElement 🤪

2021-12-06 09:39 UTC, KeziahMoselle commented on packages/docs/guide/introduction/managing-refs.md
> +    // `btn` is a single ref.
Should I also include the return type @titouanmathis ?

2021-12-06 09:56 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-refs.md
> +    // `btn` is a single ref.
I think this can be misleading here with an overload of information (maybe?) and we have the refs type described in the following examples, so I would advise not to include it.

2021-12-06 10:32 UTC, KeziahMoselle commented
I added back HTML examples in the Single ref and Multiple refs section @titouanmathis as it was not clear enough. What do you think of this version?

2022-01-17 08:13 UTC, titouanmathis approved these changes
👍

2022-01-17 08:13 UTC, merged