Add managing options content
studiometa/js-toolkit pull request #170
Opened 2021-12-06 15:02 UTC by KeziahMoselle

First draft of the managing options section of the guide.

2021-12-06 15:33 UTC, titouanmathis requested changes
A good first version, thanks for your input @KeziahMoselle 👍

2021-12-06 15:33 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-options.md
> +```
**suggestion:** List all available types and their usage

- `Boolean`: `data-option-bool` and `data-option-no-bool`, defaults to `false`
- `Number`: parsed as number, defaults to `0`
- `String`: parsed as a string, defaults to `''`
- `Array`: parsed as an array, defaults to `[]`, default value must be defined with a function
- `Object`: parsed as an object, defaults to `{}`, default value must be defined with a function

2021-12-06 15:33 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-options.md
> +      videoId: {
**suggestion:** Add a mention about simple option definition (without default value)

```
options: {
  videoId: String,
  muted: Boolean,
}
```

2021-12-06 15:33 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-options.md
> +
**suggestion:** Add a note to specify that reassigning an option is not recommended, as they should be used as initialization parameters.

For example, an internal flag `isActive` should not be an option if it is not meant to be changed in via the HTML API.

2021-12-06 15:33 UTC, titouanmathis commented on packages/docs/guide/introduction/managing-options.md
> +An option is a way to pass data to a component.
**suggestion:** Specify that it is a way to pass data from the HTML part of a component. 

Options are also a way to configure a component's behaviour at the instance level, since they are specific to each instance. 

```js
class Foo extends Base {
  static config = {
    name: 'Foo',
    options: {
      isActive: Boolean,
    },
  };

  isOpen = false;

  mounted() {
    this.isOpen; // ← instance level but shared by all instances
    this.$options.isActive; // ← instance level, can differ for each instance depending on the HTML
  }
}
```

2022-01-24 16:32 UTC, KeziahMoselle commented
@titouanmathis I made some changes, tell me what you think. I think it still needs some work

2022-02-03 08:27 UTC, titouanmathis approved these changes
Great work @KeziahMoselle! 👍

2022-02-03 08:27 UTC, merged