Add import helpers and decorators for media queries
studiometa/js-toolkit pull request #313
Opened 2022-11-07 19:14 UTC by KeziahMoselle

### Import helper

Usage:

```js
static config = {
    name: 'App',
    components: {
      AnimateComponent: () =>
        importOnMediaQuery(
          () => import('./components/AnimateScrollTest'),
          'not (prefers-reduced-motion)', // The media you want to match, here it mounts only if user accepts motion
        ),
    }
}
```

### Decorator (todo)

### Predefined import helpers and decorators for common media queries: 

- [ ] `importWhenPrefersMotion`
- [ ] `importWhenPrefersData`
- [ ] `withMountWhenPrefersMotion`
- ?

2022-11-08 14:29 UTC, KeziahMoselle commented
I don't think adding dedicated functions for `prefers-reduced-data` is worth yet considering the compatibility table: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-data#browser_compatibility

2022-11-09 11:42 UTC, titouanmathis requested changes
Really nice PR, thanks @KeziahMoselle!

2022-11-09 11:42 UTC, titouanmathis commented on packages/js-toolkit/helpers/importOnMediaQuery.ts
> +  const resolver = (resolve) => {
**nitpick:** Could you refactor the resolver management which is the same for all import helpers?

I am thinkink of a `getResolver(fn)` function in the `helpers/utils.ts` file which could be used as follow:

```ts
import { getComponentResolver } from './utils.ts';

const resolver = getComponentResolver(fn);

return new Promise((resolve) => resolver(resolve));
```

2022-11-09 11:42 UTC, titouanmathis commented on packages/js-toolkit/helpers/importOnMediaQuery.ts
> +    const { matches } = window.matchMedia(media);
**issue:** We need to listen to the change event to trigger the resolver if `matches` is falsy, as it can become truthy following a user interaction (resizing for example)

2022-11-09 11:42 UTC, titouanmathis commented on packages/js-toolkit/helpers/importWhenPrefersMotion.ts
> +export default function importWhenPrefersMotion<T extends BaseConstructor = BaseConstructor>(
**chore:** Use `importOnMediaQuery` here 

```js
export default function importWhenPrefersMotion(fn) {
  return importOnMediaQuery(fn, 'not (prefers-reduced-motion)');
}
```

2022-11-09 11:42 UTC, titouanmathis commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +      this.__mediaQueryList = window.matchMedia(this.$options.media || media);
**nitpick:** This variable does not need to be attached to the instance 

It is only used in the constructor, we can avoid adding another property to the class.

2023-02-21 17:30 UTC, titouanmathis requested changes
Some nitpicking to finalize this PR, but great work anyway! 👍

2023-02-21 17:30 UTC, titouanmathis commented on packages/docs/api/decorators/withIntersectionObserver.md
> +Or at the instance level in the `data-option-intersection-observer` attribute of the root element:
**praise:** Nice catch!

2023-02-21 17:30 UTC, titouanmathis commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +      if (!this.$options.media && !media) {
**nitpick:** Add the `isDev` condition before logging anything

2023-02-21 17:30 UTC, titouanmathis commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +        this.$log(
**suggestion:** Use the `this.$warn()` method

2023-02-21 17:30 UTC, titouanmathis commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +          setTimeout(() => this.$destroy());
**nitpick:** This line should be tested

See my comment in the spec file for an example on how to test it.

2023-02-21 17:30 UTC, titouanmathis commented on packages/tests/decorators/withMountOnMediaQuery.spec.js
> +    expect(instance.$isMounted).toBe(true);
**suggestion:** To test the missing line from the coverage with the `this.$destroy()` call

```suggestion
    expect(instance.$isMounted).toBe(true);
    matchMedia.useMediaQuery('(prefers-reduced-motion)');
    await wait(0);
    expect(instance.$isMounted).toBe(false);
```

2023-02-21 17:30 UTC, titouanmathis commented on packages/tests/decorators/withMountOnMediaQuery.spec.js
> +    expect(instance.$isMounted).toBe(false);
**suggestion:** To make sure that a component can be mounted again after a change in a media query, it might be interesting to add a few lines here

```suggestion
    expect(instance.$isMounted).toBe(false);
    matchMedia.useMediaQuery(mediaQuery);
    await wait(0);
    expect(instance.$isMounted).toBe(true);
```

2023-02-22 12:44 UTC, KeziahMoselle commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +      if (!this.$options.media && !media) {
Isn't this log conditional already with the `log` option in the Class definition?

2023-02-22 13:43 UTC, titouanmathis commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +      if (!this.$options.media && !media) {
It is indeed conditioned by the `this.$options.log` value. The `isDev` condition is different: the log will only be logged when in dev or watch mode, but the whole lines will be dropped (considered as dead code) in the final bundle when building for production.

This strategy is used for other debug and warning logs.

2023-02-22 14:00 UTC, KeziahMoselle commented on packages/js-toolkit/decorators/withMountOnMediaQuery.ts
> +      if (!this.$options.media && !media) {
Oh okay, that's very good to know! Adding this

2023-02-23 10:02 UTC, titouanmathis requested changes

2023-02-24 15:38 UTC, titouanmathis approved these changes

2023-02-24 15:40 UTC, titouanmathis requested changes
@KeziahMoselle could you update the changelog as well?

2023-02-24 16:14 UTC, merged