[Feature] Warning helper
studiometa/js-toolkit pull request #335
Opened 2023-01-04 14:56 UTC by antoine4livre

## Added

- **Base:**
  - Add the `$warn()` helper ([1071c75](https://github.com/studiometa/js-toolkit/commit/1071c75))

2023-01-04 15:38 UTC, titouanmathis requested changes
Great addition @antoine4livre! 👍

2023-01-04 15:38 UTC, titouanmathis commented on CHANGELOG.md
> +  - Add the `$warn()` helper ([1071c75](https://github.com/studiometa/js-toolkit/commit/1071c75))
**nitpick:** Same as in studiometa/ui, prefer a reference to a PR when possible

```suggestion
  - Add the `$warn()` helper ([#335](https://github.com/studiometa/js-toolkit/pull/335))
```

2023-01-04 15:38 UTC, titouanmathis commented on packages/docs/api/instance-methods.md
> +    this.$warn('Warning !');
**suggestion:** Add a comment showing what will be logged to the console 

```suggestion
    this.$warn('Warning!'); // [Component-1] Warning!
```

2023-01-04 15:38 UTC, titouanmathis commented on packages/js-toolkit/Base/index.ts
> +  get $warn(): (...args: unknown[]) => void {
**issue (blocking):** Add tests to ensure the implementation will not break later

You can duplicate the tests for the `this.$log()` method in the `packages/tests/Base/index.spec.js` file. You will find them at the line 435 and 451:

```js
it('should have a working $log method when active', () => {
  // ...
});

it('should have a silent $log method when not active', () => {
  // ...
});
```

2023-01-11 16:19 UTC, antoine4livre commented on packages/js-toolkit/Base/index.ts
> +  get $warn(): (...args: unknown[]) => void {
Done !

2023-01-11 16:27 UTC, titouanmathis requested changes
The unit test pipeline is failing, some snapshots are outdated following the new tests. Could your run the following command locally @antoine4livre?

```sh
npm run test -- -- -u
```

You should then have a change `*.snap` file that you can commit, this should fix the tests.

2023-01-25 16:35 UTC, titouanmathis commented
@antoine4livre could you rebase your branch on `develop` to fix the conflicts? The `Base/index.ts` file has been renamed `Base/Base.ts`.

2023-01-25 17:27 UTC, titouanmathis approved these changes
👍

2023-01-25 17:27 UTC, titouanmathis commented on CHANGELOG.md
> +- Add the `$warn()` helper ([#335](https://github.com/studiometa/js-toolkit/pull/335))
**nitpick:** Add a `**Base:**` prefix to the changelog entry for easier discovery of new things

```suggestion
- **Base:** add a `$warn()` helper ([#335](https://github.com/studiometa/js-toolkit/pull/335))
```

2023-01-25 17:33 UTC, merged