[Feature] `tweenScrollTo` utility, `cssScrollTo` utility and `rootElement` option on `scrollTo` utilities
studiometa/js-toolkit pull request #418
Opened 2024-03-20 16:31 UTC by antoine4livre

2024-03-20 18:03 UTC, titouanmathis requested changes

2024-03-20 18:03 UTC, titouanmathis commented on packages/js-toolkit/utils/scrollTo/tweenScrollTo.ts
> +        window.scrollTo({ top: lerp(window.scrollY, scrollTarget, progress) });
**issue :** You need to save the value of `window.scrollY` before the tween starts

Otherwise, it will always be the latest value and the scroll animation might behave strangely.

2024-03-27 19:48 UTC, antoine4livre commented
@titouanmathis We need to talk about the next modifications like #173 & #261.

What do you think about this new implementation ?

2024-03-28 09:51 UTC, titouanmathis requested changes

2024-03-28 09:51 UTC, titouanmathis commented on packages/js-toolkit/utils/scrollTo.ts
> +export type TweenScrollToOptions = TweenOptions & {
**nitpick:** Rename the type to `ScrollToOptions`

2024-03-28 09:51 UTC, titouanmathis commented on packages/js-toolkit/utils/scrollTo.ts
> +      resolve(getCurrentScrollPosition());
**suggestion:** refactor this part in a `stop` function 

It is used both in the `eventHandler` function and the `onFinish` hook.

2024-03-28 09:51 UTC, titouanmathis commented on packages/tests/utils/scrollTo.spec.ts
> +    await scrollTo('div');
**suggestion :** Keep the use of the fake timers to speed up test execution

```js
useFakeTimers();
scrollTo('div', { duration: 1 });
await advanceTimersByTimeAsync(1016);
expect(fn).toHaveBeenLastCalledWith({ left: 0, top: 5000 });
useRealTimers();
```

2024-03-28 10:15 UTC, antoine4livre commented on packages/js-toolkit/utils/scrollTo.ts
> +export type TweenScrollToOptions = TweenOptions & {
ScrollToOptions is already the type of options for `window.scrollTo`, is it ok ?

2024-03-28 10:18 UTC, antoine4livre commented on packages/tests/utils/scrollTo.spec.ts
> +    await scrollTo('div');
Tween don't use timers right ? I can't make this fake timers work.

2024-04-03 16:01 UTC, merged