Collide utils
studiometa/js-toolkit pull request #83
Opened 2021-04-12 09:59 UTC by antoine4livre

2021-05-17 14:12 UTC, titouanmathis commented
@antoine4livre I rebased your feature on develop to include the recent changes in the folder structure and to avoid conflicts.
Your force pushes undid these changes, you should rebase again in order for the Netlify builds to pass.

2021-05-31 10:27 UTC, antoine4livre commented
I think that it is finished @titouanmathis, if you want to review it.

2021-05-31 13:26 UTC, titouanmathis requested changes
Seems all good to me! 

There is one typo that prevents the test from passing, but it should be good afterwards.

2021-05-31 13:26 UTC, titouanmathis commented on packages/js-toolkit/utils/collide/index.js
> +import collidePointRect from './collidePointRect.js;
**issue:** There is a missing closing quote here

2021-05-31 14:06 UTC, titouanmathis commented
@antoine4livre Could you update the `tests/utils/index.spec.js` test to include the new `collide` export ?

2021-06-21 15:25 UTC, merged